### ISSUE TITLE
[其他反馈]

### ISSUE THREAD

**Issue by XiaoWu520233** [MetsukiMio/Advanced-Framework#6]
![QQ截图20240623132303](https://github.com/PrimogemStudio/Advanced-Framework/assets/136713371/430e0847-be6a-4791-9ded-ca4e13721087)
![QQ截图20240623132557](https://github.com/PrimogemStudio/Advanced-Framework/assets/136713371/7a995662-b58f-4136-9356-b19d98241a90)
![QQ截图20240623132614](https://github.com/PrimogemStudio/Advanced-Framework/assets/136713371/7d21b81c-f781-450d-b171-450bce32351b)
加了这些MOD这个模组就不能正常加载，望解决，谢谢！

**Comment by Jack253-png** [comment]
请问能不能提供完整日志，日志核心部分没有展现出来（

**Comment by hackermdch** [comment]
由于长时间无回复，关闭此主题。
